// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VersionInserterVSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVersionInserterVSIXPackageString = "c52aace7-0224-403a-874a-d010dab838bf";
        public static Guid guidVersionInserterVSIXPackage = new Guid(guidVersionInserterVSIXPackageString);

        public const string guidVersionInserterVSIXPackageCmdSetString = "a2ec2c7e-3b1f-46f0-90c5-2277e5769611";
        public static Guid guidVersionInserterVSIXPackageCmdSet = new Guid(guidVersionInserterVSIXPackageCmdSetString);

        public const string guidImagesString = "0f60d402-c5c7-43c1-8669-d78f01d9161f";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int InsertMigrationVersionCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}